### ISSUE TITLE
Date#getDate starts at 1

### ISSUE THREAD

**Issue by bbenezech** [brunofacca/zen-rails-base-app#1]
https://github.com/brunofacca/zen-rails-base-app/blob/0cc891173d53e18dca16378adabdb042e7541e4e/app/assets/javascripts/zen-utils.js#L47

```javascript
d = new Date()
>> Tue Aug 29 2017 16:31:22 GMT+0200 (CEST)
d.getDate()
>> 29
```

You are correct about months, though.

**Comment by brunofacca** [comment]
I'm glad you have noticed it. Thank you.
