### ISSUE TITLE
How to list all the users 

### ISSUE THREAD

**Issue by shashankshandilyav** [brunofacca/zen-rails-base-app#12]
Hey sorry, it's not actually an issue. I don't know how to reach you in person.I am using your base app Its really amazing thank you  
I have to do the list all the users from the database and show their details, could you guide me the best possible way to do this as of now admin has all the power to CRUD the user but I need to have the show and index action for the nonadmin user. And have to use all the powers of pundit. 
I know it's not related to your repository but  It could really help me. Thanks in advance

**Comment by brunofacca** [comment]
Hi @shashankshandilyav, 

I'm glad you liked the app.

To achieve what you want, you should move `UsersController` outside of the `admin` namespace then edit `app/policies/user_policy.rb` to allow non-admin users to access specific actions of that controller. Wish I had more time to provide greater details.
