### ISSUE TITLE
missing sweetalert2 gem in Gemfile?

### ISSUE THREAD

**Issue by bjpcjp** [brunofacca/zen-rails-base-app#2]
I did a localhost install in 8/29. localhost:3000/users/sign_in fails with the following msg:
>  couldn't find file 'sweetalert2/dist/sweetalert2' with type 'text/css'

/assets/stylesheets/aplication.scss includes the following :
> *= require sweetalert2/dist/sweetalert2

I didn't see this gem in Gemfile. Did I miss something?

**Comment by brunofacca** [comment]
SweetAlert2 is installed via Yarn. 

1. Install yarn by following [these instructions](https://yarnpkg.com/en/docs/install) 
2. cd to the application root directory and run `yarn install`. 

I will add the `yarn install` step to the README.
