### ISSUE TITLE
Seed file contains duplicate email addresses

### ISSUE THREAD

**Issue by stmcintyre** [brunofacca/zen-rails-base-app#3]
Seed file has 'admin@test.com' for both the Admin and Ordinary user.  This results the following error whilst trying to seed:

**_ActiveRecord::RecordInvalid: Validation failed: E-mail has already been taken_**

I believe the correct email for the ordinary user should be 'user@test.com' as per the Readme.

Thanks for taking the time to set this base app up and sharing.  I'll create a small PR to fix the typo.

**Comment by brunofacca** [comment]
I'm glad you have spotted that typo.  Thanks for the PR.

**Comment by brunofacca** [comment]
PR merged. Thank you :)
