### ISSUE TITLE
12 factor, docker, etc.

### ISSUE THREAD

**Issue by Ilya-Kuchaev** [brunofacca/zen-rails-base-app#8]
What about to add Dockerfile, docker-compose.yml, etc.?

**Comment by brunofacca** [comment]
I'm currently using [this development environment](https://github.com/brunofacca/rails-development-environment) and deploying to Heroku or Amazon Elastic Beanstalk. So Docker is not a part of my workflow and I currently do not have enough knowledge to implement it. However, I intend to learn it and eventually, replace Vagrant by Docker.
